name: CI

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - {
              scheme: "ImageViewer",
              destination: "platform=iOS Simulator,OS=17.4,name=iPhone 15",
            }
    steps:
      - uses: actions/checkout@v4
      - name: Show Available Destinations
        env:
          scheme: ${{ matrix.run-config['scheme'] }}
        run: xcodebuild -scheme ${scheme} -showdestinations
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
